### ISSUE TITLE
me endpoint

### ISSUE THREAD

**Issue by Gerst20051** [oauth-io/sdk-php#9]
the me endpoint still doesn't work for me... how do i get this to use the data provided in the **me.js** files. i've found out that this file is returned when i do the following request but i can't find anything else that uses it.

https://domain.com:6284/api/providers/:provider/user-mapping

i've tried both of the available methods:

`$req->get('/me')`
`$req->me()`

i also don't think the **me.js** files are completely accurate.

**Comment by Gerst20051** [comment]
I'm looking into what's happening but I get this error when I navigate to the following url: https://andrew.website.com:6284/auth/twitter/me

``` json
{
status: "error",
code: 500,
message: "Cannot read property 'Error' of undefined",
data: {
code: "InternalError"
}
}
```

It's probably running into this block and `check` is undefined.

``` javascript
return cb(new check.Error('Error in request parameters'));
```

**Comment by Gerst20051** [comment]
@william26 

I'll try `$req->me()` again.

Line 128

``` php
    public function me($filters = null) {
        $response = $this->makeMeRequest($filters)->body->data;
        return $this->object_to_array($response);
    }
```

# ME RESPONSES

## FACEBOOK

`PHP Notice:  Undefined property: stdClass::$data in /home/ubuntu/v2/mobile/oauth/src/OAuth_io/RequestObject.php on line 128`
`REQ ME = null`

CURL - UNIREST - URL = https://andrew.website.com:6284/request/facebook/me
URL SHOULD BE: https://andrew.website.com:6284/request/facebook/%2Fme
**FB URLS ARE THE SAME SO WHAT'S FAILING WITH THE ME METHOD?**

## TWITTER

`PHP Notice:  Trying to get property of non-object in /home/ubuntu/v2/mobile/oauth/src/OAuth_io/RequestObject.php on line 128`
`REQ ME = null`

CURL - UNIREST - URL = https://andrew.website.com:6284/request/twitter/me
URL SHOULD BE: https://andrew.website.com:6284/request/twitter/%2F1.1%2Faccount%2Fverify_credentials.json

**$this->makeMeRequest($filters)** = Unirest\HttpResponse Object(    [code:Unirest\HttpResponse:private] => 404    [raw_body:Unirest\HttpResponse:private] => <!DOCTYPE html>

## GOOGLE PLUS

`PHP Notice:  Trying to get property of non-object in /home/ubuntu/v2/mobile/oauth/src/OAuth_io/RequestObject.php on line 128`
`REQ ME = null`

CURL - UNIREST - URL = https://andrew.website.com:6284/request/google_plus/me
URL SHOULD BE: https://andrew.website.com:6284/request/google_plus/%2Fplus%2Fv1%2Fpeople%2Fme

**$this->makeMeRequest($filters)** = Unirest\HttpResponse Object(    [code:Unirest\HttpResponse:private] => 404    [raw_body:Unirest\HttpResponse:private] => Not Found    [body:Unirest\HttpResponse:private] => Not Found    [headers:Unirest\HttpResponse:private] => Array        (            [content-type] => text/html; charset=UTF-8            [cache-control] => no-cache, no-store, max-age=0, must-revalidate            [pragma] => no-cache            [expires] => Fri, 01 Jan 1990 00:00:00 GMT            [date] => Fri, 08 Aug 2014 15:31:19 GMT            [content-encoding] => gzip            [x-content-type-options] => nosniff            [x-frame-options] => SAMEORIGIN            [x-xss-protection] => 1; mode=block            [server] => GSE            [alternate-protocol] => 443:quic            [transfer-encoding] => chunked            [Access-Control-Allow-Origin] => http://localhost            [Access-Control-Allow-Methods] => GET, POST, PUT, PATCH, DELETE            [Connection] => keep-alive        ))

## PAYPAL

`PHP Fatal error:  Uncaught exception 'Exception' with message 'Empty reply from server' in /home/ubuntu/v2/mobile/oauth/lib/Unirest/Unirest.php:220Stack trace:#0 /home/ubuntu/v2/mobile/oauth/lib/Unirest/Unirest.php(60): Unirest::request('GET', 'https://andrew....', NULL, Array, NULL, NULL)#1 /home/ubuntu/v2/mobile/oauth/src/OAuth_io/HttpWrapper.php(34): Unirest::get('https://andrew....', Array)#2 /home/ubuntu/v2/mobile/oauth/src/OAuth_io/RequestObject.php(96): OAuth_io\HttpWrapper->make_request(Array)#3 /home/ubuntu/v2/mobile/oauth/src/OAuth_io/RequestObject.php(128): OAuth_io\RequestObject->makeMeRequest(NULL)#4 /home/ubuntu/v2/mobile/oauth/index.php(37): OAuth_io\RequestObject->me()#5 /home/ubuntu/v2/mobile/oauth/index.php(173): getMeData(Object(OAuth_io\RequestObject), 'paypal')#6 {main}  thrown in /home/ubuntu/v2/mobile/oauth/lib/Unirest/Unirest.php on line 220`

CURL - UNIREST - URL = https://andrew.website.com:6284/request/paypal/me
URL SHOULD BE: https://andrew.website.com:6284/request/paypal/%2Fv1%2Fidentity%2Fopenidconnect%2Fuserinfo%2F%3Fschema%3Dopenid
